version: '3.8'
services:
  web:
    image: homebrewsoft/odoo:14.0
    container_name: odoo
    hostname: odoo
    ports:
      - 3231:8069
    depends_on:
      - db
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

  db:
    image: postgres:13.4
    container_name: odoo_db
    hostname: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  web-data:
  db-data:

